# Site settings
title: Wilfred Gabriel A. Gapas - teacher, writer, researcher, cat lover
email: wgabrielgapas@gmail.com
description: The personal academic homepage of Wilfred Gabriel A. Gapas, an MA candidate in English Language Studies at the University of Santo Tomas, Manila. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: senseigab
github_username:  senseigab

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed